---

- name: "Configure {{ item.file }}"
  template:
    src: "{{ item.name }}-site.xml.j2"
    dest: "{{ item.file }}"
    validate: "xmllint %s"
  when:
    - item.file is defined
    - item.file | length > 0
  register: hadoop_site
  notify:
    - Restart journalnode
  with_items:
    - { name: 'core', file: "{{ hadoop_core_site_file }}" }
    - { name: 'hdfs', file: "{{ hadoop_hdfs_site_file }}" }
    - { name: 'mapred', file: "{{ hadoop_mapred_site_file }}" }
    - { name: 'yarn', file: "{{ hadoop_yarn_site_file }}" }
