---
# tasks file for ansible-role-hadoop_journalnode

- include_vars: "{{ ansible_os_family }}.yml"

- include: install-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- name: Create log directory
  file:
    path: "{{ hadoop_journalnode_log_dir }}"
    mode: 0755
    owner: "{{ hadoop_journalnode_user }}"
    group: "{{ hadoop_journalnode_group }}"
    state: directory
  notify: Restart journalnode

- name: Create db directory
  file:
    path: "{{ hadoop_journalnode_db_dir }}"
    mode: 0755
    owner: "{{ hadoop_journalnode_user }}"
    group: "{{ hadoop_journalnode_group }}"
    state: directory
  notify: Restart journalnode

- include: configure-xml.yml

- name: Start journalnode
  service:
    name: "{{ hadoop_journalnode_service }}"
    enabled: true
    state: started
